### PR TITLE
[FSDP2/Megatron-FSDP/DCP] If model parameters are DTensors, optimizer states should also be DTensors.

### PR DESCRIPTION
**Pull request by cspades**
# Description

- Fixes a bug introduced by the new `DTensor(QuantizedTensor)` (FSDP2-only) use case introduced in https://github.com/NVIDIA/TransformerEngine/pull/2698 where `FusedAdam`'s optimizer state is converted into a non-distributed Tensor, which is loaded as a global state dictionary by Torch DCP.

This will break Megatron-FSDP checkpointing with DCP in MLM:
```
[rank0]:   File "/opt/megatron-lm/megatron/training/checkpointing.py", line 1015, in preprocess_fsdp_dtensor_state_dict
[rank0]:     model_state_dict, optimizer_state_dict = handle_swiglu_in_state_dict(
[rank0]:                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/megatron-lm/megatron/core/transformer/fsdp_dtensor_checkpoint.py", line 318, in handle_swiglu_in_state_dict
[rank0]:     weight_w, weight_v = split_swiglu_linear_fc1(
[rank0]:                          ^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/megatron-lm/megatron/core/transformer/fsdp_dtensor_checkpoint.py", line 246, in split_swiglu_linear_fc1
[rank0]:     local_tensor = data.to_local()
[rank0]:                    ^^^^^^^^^^^^^
[rank0]: AttributeError: 'Tensor' object has no attribute 'to_local'
```
and causes FSDP2 to not have a distributed optimizer state. (See re-shard tests.)

## Details

- We wrap the optimizer state as a DTensor matching the distribution characteristics of the original DTensor parameter the state is associated with. So the state is always a DTensor while its compute and steps are applied to the local Tensor. (There are very few line changes if you ignore variable renaming.)
- Test Structure
  - `dcp_resharding_save` must be run with and before `dcp_resharding_load`.
  - `dcp_resharding_save` deletes existing checkpoint directories, and write a new DCP checkpoint, while `dcp_resharding_load` `finally` deletes the saved DCP checkpoint as well.

## Testing

- TE CI/CD
```
TE_PATH=/workspace/TransformerEngine ./qa/L1_pytorch_distributed_unittest/test.sh

OR

pytest -v -s tests/pytorch/distributed/test_torch_fsdp2.py::test_fsdp2_fused_adam_dcp_resharding
```
- Megatron-LM + `--use-precision-aware-optimizer`
```
# TE@00ba0b493c27f32e2f210b0022132c50da78dac7 (Llama 8B + Precision-Aware Optimizer + FP8Blockwise + TP2 + GB300)
[2026-03-25 15:18:07.588704] iteration      100/15258789 | consumed samples:        12800 | elapsed time per iteration (ms): 9614.0 | throughput per GPU (TFLOP/s/GPU): 1403.6 | learning rate: 4.915198E-07 | global batch size:   128 | lm loss: 1.131176E+00 | loss scale: 1.0 | grad norm: 5.337 | number of skipped iterations:   0 | number of nan iterations:   0 |

# This PR (Llama 8B Precision-Aware Optimizer + FP8Blockwise + TP2 + GB300)
[2026-03-25 14:58:55.856189] iteration      100/15258789 | consumed samples:        12800 | elapsed time per iteration (ms): 9588.0 | throughput per GPU (TFLOP/s/GPU): 1407.4 | learning rate: 4.915198E-07 | global batch size:   128 | lm loss: 1.131045E+00 | loss scale: 1.0 | grad norm: 5.336 | number of skipped iterations:   0 | number of nan iterations:   0 |
```
- This PR fixes the Megatron-FSDP un-even DTensor preprocessing error, and training works fine:
```
# Megatron-FSDP + self.use_precision_aware_optimizer=True + --use-precision-aware-optimizer + BF16 + HFSDP
# And: --save-interval 1 and --ckpt-format fsdp_dtensor to reproduce the checkpointing error quickly.
[2026-03-31 08:37:02.253124] iteration        3/15258789 | consumed samples:          384 | elapsed time per iteration (ms): 18363.2 | throughput per GPU (TFLOP/s/GPU): 734.8 | learning rate: 1.474559E-08 | global batch size:   128 | lm loss: 1.213362E+01 | loss scale: 1.0 | grad norm: 0.000 | num zeros: 0 | number of skipped iterations:   0 | number of nan iterations:   0 |
```
- To reproduce the FSDP2 error motivating this PR, use the broken FusedAdam code before this PR/commit and run this test that saves a checkpoint with 4 GPUs and loads the saved checkpoint with 2 GPUs:
```
torchrun --nproc-per-node 4 -m pytest tests/pytorch/distributed/fsdp2_tests/run_fsdp2_fused_adam.py -v -s -k "dcp_resharding_save" && torchrun --nproc-per-node 2 -m pytest tests/pytorch/distributed/fsdp2_tests/run_fsdp2_fused_adam.py -v -s -k "dcp_resharding_load"

E               raise ValueError(
E           ValueError: Size mismatch between saved torch.Size([64]) and current: torch.Size([128]) for optimizer.state.0.exp_avg
E           Traceback (most recent call last): (RANK 1)
E             File "/usr/local/lib/python3.12/dist-packages/torch/distributed/checkpoint/utils.py", line 193, in reduce_scatter
E               local_data = map_fun()
E                            ^^^^^^^^^
E             File "/usr/local/lib/python3.12/dist-packages/torch/distributed/checkpoint/logger.py", line 90, in wrapper
E               result = func(*args, **kwargs)
E                        ^^^^^^^^^^^^^^^^^^^^^
E             File "/usr/local/lib/python3.12/dist-packages/torch/distributed/checkpoint/state_dict_loader.py", line 269, in local_step
E               local_plan = planner.create_local_plan()
E                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
E             File "/usr/local/lib/python3.12/dist-packages/torch/distributed/checkpoint/default_planner.py", line 352, in create_local_plan
E               return create_default_local_load_plan(
E                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E             File "/usr/local/lib/python3.12/dist-packages/torch/distributed/checkpoint/default_planner.py", line 485, in create_default_local_load_plan
E               raise ValueError(
E           ValueError: Size mismatch between saved torch.Size([64]) and current: torch.Size([128]) for optimizer.state.0.exp_avg
```

## Type of change

- [ ] Documentation change (change only to the documentation, either a fix or a new content)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Infra/Build change
- [ ] Code refactoring

# Checklist:

- [ ] I have read and followed the [contributing guidelines](https://github.com/NVIDIA/TransformerEngine/blob/main/CONTRIBUTING.rst)
- [ ] The functionality is complete
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by cspades** [comment]
/te-ci L1 pytorch -> https://gitlab-master.nvidia.com/dl/transformerengine/transformerengine/-/pipelines/46894290

File: transformer_engine/pytorch/optimizers/fused_adam.py [hunk 1]
```diff
@@ -374,12 +377,18 @@ def set_scaled_state(self, param, state_name, unscaled_state):
         if state_name not in state:
             self._initialize_state(param, state_name, False, store_param_remainders)
 
+        # If the original Parameter is a DTensor, retrieve the local Tensor
+        # of the state (which is also DTensor) for scaling.
+        local_state = state[state_name]
+        if isinstance(param, DTensor):
+            local_state = local_state._local_tensor
```
[the remark this answers is not in the document]
Comment (vthumbe1503) [reply transformer_engine/pytorch/optimizers/fused_adam.py]: I guess we should include a guard that checks if both param and state are similar, in sense either both are Dtensors or both are not, otherwise throw error @cspades ?

File: transformer_engine/pytorch/optimizers/fused_adam.py [hunk 2]
```diff
@@ -418,9 +428,19 @@ def _initialize_state(
             self.state[param][state_name] = quantizer.make_empty(param.shape)
             self.state[param][state_name].quantize_(data.float())
```
[the remark this answers is not in the document]
Comment (vthumbe1503) [reply transformer_engine/pytorch/optimizers/fused_adam.py:428]: Looks like a valid fix @cspades ?

**Comment by vthumbe1503** [comment]
@cspades could you please elaborate on the downstream error/issue caused. As in what happens if we load the unsharded tensor for optimizer state as plain tensor instead of DTensor?

**Comment by cspades** [comment]
> @cspades could you please elaborate on the downstream error/issue caused. As in what happens if we load the unsharded tensor for optimizer state as plain tensor instead of DTensor?

Here is how I understand it, @shjwudp correct me if I am wrong about the Megatron-FSDP details, as I still need to reproduce the bug and ensure this PR fixes it. I believe a customer reported this bug?

- https://github.com/NVIDIA/TransformerEngine/pull/2698 introduced logic during the `FusedAdam.__init__` such that if the TE model parameters are `DTensor`, then it will change the optimizer state to normal `Tensor`.
  - The reason is because `empty_like` does not pick up the correct `dtype` from `DTensor` (from in-line commentary), when the local data is `QuantizedTensor`. Note that Megatron-FSDP's main weights are FP32, not `QuantizedTensor`, so our code worked with the original `FusedAdam`.
- When Megatron-FSDP (or Megatron-LM's distributed optimizer) performs its first `optimizer.step()`, Megatron-FSDP exposes FP32 `DTensor` main weights to the `FusedAdam` optimizer, and because of the above logic, normal `Tensor` optimizer states are constructed from the `DTensor` main weights.
- Megatron-FSDP depends on `DTensor` optimizer states for DCP checkpointing of `FusedAdam`'s state, because we employ un-even sharding. Instead, it now sees normal `Tensors`, and this may break our DCP integration and/or un-even `DTensor` metadata.

The fix is to keep the optimizer state in `DTensor` form if the model is in `DTensor` form, and localize or perform in-place operations to the local `Tensor` for all `FusedAdam` operations.

File: transformer_engine/pytorch/optimizers/fused_adam.py (hunk 2 above)
[the remark this answers is not in the document]
Comment (cspades) [reply transformer_engine/pytorch/optimizers/fused_adam.py:428]: Huh, isn't this also wrong before? Indeed should be `data.shape()`.

File: transformer_engine/pytorch/optimizers/fused_adam.py (hunk 1 above)
[the remark this answers is not in the document]
Comment (cspades) [reply transformer_engine/pytorch/optimizers/fused_adam.py]: SGTM.

**Comment by cspades** [comment]
/te-ci L1 pytorch -> https://gitlab-master.nvidia.com/dl/transformerengine/transformerengine/-/pipelines/46983332

File: tests/pytorch/distributed/fsdp2_tests/run_fsdp2_fused_adam.py [hunk 3]
```diff
@@ -740,6 +746,207 @@ def test_dcp_output_parity(recipe_name, async_save):
...
+    a *different* world_size (typically half as many ranks) to verify that DCP
+    correctly reshards the checkpoint into the new topology.
+
+    The two phases are orchestrated by test_fsdp2_fused_adam_dcp_resharding in
+    test_torch_fsdp2.py using two sequential torchrun invocations.
+    """
+    recipe = get_recipe_from_string(recipe_name)
+
+    if recipe_name == "MXFP8BlockScaling":
+        pytest.xfail(
```
Comment (jomitchellnv) [inline tests/pytorch/distributed/fsdp2_tests/run_fsdp2_fused_adam.py]: Once PR https://github.com/NVIDIA/TransformerEngine/pull/2789 gets merged this should be passing though right?

**Comment by cspades** [comment]
https://gitlab-master.nvidia.com/dl/transformerengine/transformerengine/-/pipelines/47362013

Some random error:
```
ERROR: file or directory not found: /opt/pytorch/lightning-thunder/thunder/tests/test_transformer_engine_executor.py
```
Rebased and rerunning CI.

**Comment by cspades** [comment]
/te-ci L1 pytorch -> https://gitlab-master.nvidia.com/dl/transformerengine/transformerengine/-/pipelines/47378370

**Comment by cspades** [comment]
/te-ci L1 pytorch -> https://gitlab-master.nvidia.com/dl/transformerengine/transformerengine/-/pipelines/47383028

**Comment by cspades** [comment]
https://gitlab-master.nvidia.com/dl/transformerengine/transformerengine/-/pipelines/47670017 🙏🏻

File: tests/pytorch/distributed/test_torch_fsdp2.py [hunk 4]
```diff
@@ -83,13 +90,81 @@ def test_fsdp2_mem_leak_tests():
             "-v",
             "-s",
             "--tb=short",
+            # The following 2 tests need to be run in sequence,
+            # as they depend on each other.
+            "-k",
+            "not dcp_resharding_save and not dcp_resharding_load",
```
Comment (cspades) [inline tests/pytorch/distributed/test_torch_fsdp2.py]: This is wrong, it should be for `test_fsdp2_fused_adam_tests`! Rebase error: https://gitlab-master.nvidia.com/dl/transformerengine/transformerengine/-/jobs/292224131/viewer

**Comment by cspades** [comment]
/te-ci L1 pytorch -> https://gitlab-master.nvidia.com/dl/transformerengine/transformerengine/-/pipelines/47678738 (Fixed misplaced filters.)
